default:
  shader: presets/rgc_glow_crt

gamegear:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
pokemini:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gb: 
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gbc:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gba:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
virtualboy: 
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
nds:
  shader: /usr/share/batocera/shaders/handheld/lcd1x_nds
psp:
  shader: /usr/share/batocera/shaders/handheld/lcd1x_psp
lynx:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gamate:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gmaster:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
supervision:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
megaduck: 
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gamecom:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
ngpc:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
ngp:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
wswan:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
wswanc:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
gp32:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
arduboy:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
lowresnx:
  shader: /usr/share/batocera/shaders/sharp-shimmerless/shaders_glsl/shaders/sharp-shimmerless-grid.glsl
lutro:
  shader: none
pico8:
  shader: none
tic80:
  shader: none
uzebox:
  shader: none
vircon32:
  shader: none
scummvm:
  shader: none
zmachine:
  shader: none
gameandwatch:
  shader: none
lcdgames:
  shader: none 